# Generated by Django 3.0.1 on 2019-12-30 01:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wichtelgruppe',
            fields=[
                ('budget', models.IntegerField()),
                ('ablaufdatum', models.DateField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Wichtelgruppenmember',
            fields=[
                ('vorname', models.CharField(max_length=20)),
                ('nachname', models.CharField(max_length=20)),
                ('emailAdress', models.EmailField(max_length=40)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wichtelgruppe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wichtelit.Wichtelgruppe')),
            ],
        ),
    ]
