# Generated by Django 3.0.1 on 2019-12-30 02:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wichtelit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wichtelmember',
            fields=[
                ('vorname', models.CharField(max_length=20)),
                ('nachname', models.CharField(max_length=20)),
                ('emailAdress', models.EmailField(max_length=40)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wichtelgruppe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wichtelit.Wichtelgruppe')),
                ('wichtelpartner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wichtelit.Wichtelmember')),
            ],
        ),
        migrations.DeleteModel(
            name='Wichtelgruppenmember',
        ),
    ]
