# Generated by Django 3.0.1 on 2019-12-30 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wichtelit', '0002_auto_20191230_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='wichtelgruppe',
            name='wichteldatum',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
