# Generated by Django 3.0.1 on 2020-01-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wichtelit', '0003_wichtelgruppe_wichteldatum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wichtelgruppe',
            name='budget',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
