# Generated by Django 3.0.1 on 2020-01-25 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wichtelit', '0004_auto_20200125_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wichtelmember',
            old_name='emailAdress',
            new_name='emailAddress',
        ),
    ]
