# Generated by Django 3.0.1 on 2020-02-29 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wichtelit', '0005_auto_20200125_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wichtelmember',
            old_name='emailAddress',
            new_name='emailAdresse',
        ),
    ]
