# Generated by Django 3.0.5 on 2020-05-03 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wichtelit', '0006_wichtelgruppe_status'),
        ('wichtelit', '0006_auto_20200229_1850'),
    ]

    operations = [
    ]
