# Generated by Django 3.0.6 on 2020-05-05 16:48

from django.db import migrations
import django_enum_choices.choice_builders
import django_enum_choices.fields
import wichtelit.models


class Migration(migrations.Migration):

    dependencies = [
        ('wichtelit', '0007_merge_20200503_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='wichtelmember',
            name='status',
            field=django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('erstellt', 'erstellt'), ('gewürfelt', 'gewürfelt'), ('email_versendet', 'email_versendet'), ('letzte_email', 'letzte_email')], default=wichtelit.models.Status['ERSTELLT'], enum_class=wichtelit.models.Status, max_length=15),
        ),
        migrations.AlterField(
            model_name='wichtelgruppe',
            name='status',
            field=django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('erstellt', 'erstellt'), ('gewürfelt', 'gewürfelt'), ('email_versendet', 'email_versendet'), ('letzte_email', 'letzte_email')], default=wichtelit.models.Status['ERSTELLT'], enum_class=wichtelit.models.Status, max_length=15),
        ),
    ]
